# Generated by Django 2.2.1 on 2019-06-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgeauction',
            name='auction_number',
            field=models.CharField(max_length=32),
        ),
    ]
