# Generated by Django 2.2.1 on 2019-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20190608_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgeauction',
            name='auction_date_open',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pgeauction',
            name='auction_date_publish',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pgeauction',
            name='auction_date_put',
            field=models.CharField(max_length=32),
        ),
    ]
